### PR TITLE
Various refactorings considering modern C++ practices

### PR DESCRIPTION
**Pull request by eneshecan**
This PR includes various code modernizations considering the modern C++ practices;
* Add clang-tidy and clang-format files to the repo
* Cleanup unused variables and function declarations without a definition
* Apply modern C++ syntax in some places instead of C syntax
* Add a newline to the end of files
* Initialize uninitialized variables
* etc.

### CODE REVIEW

**Comment by vaxerski** [comment]
I really don't like the `{}` initializers. What's the point??

**Comment by eneshecan** [comment]
It's clean and default initializes the data. Even better:
`auto x = MyStruct{};`

However, I didn't do that since I see that you don't use auto which I highly suggest otherwise.

**Comment by vaxerski** [comment]
no need to init data that will be init later.

**Comment by eneshecan** [comment]
Well, uninitialized variables are generally bad practice as suggested here https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-always. It's still the case even when you know if it will be initialized later since some modification to the code later might lead to using that variable before it's initialized. So, it makes the code cleaner, maintainable, and less error-prone.

**Comment by vaxerski** [comment]
k

**Pull request merged**
