### PR TITLE
Fix crashing when setting wallpaper

### PR DESCRIPTION
**Pull request by cijo7**
fix SIGSEGV.

### CODE REVIEW

**Comment by vaxerski** [comment]
We should probably round this JIC.

**Comment by TheSunCat** [comment]
Hm, I'm still getting a segfault with this patch, at `CHyprpaper::renderWallpaperForMonitor(SMonitor*)`.

Logs:
```
[LOG] Welcome to hyprpaper!
built from commit 3fdf9837e45d14f909cb8aa00e625128e023f7dc (    Update Hyprpaper.cpp)
[LOG] Cleaned old hyprpaper preloads (4), removing 65.4MB
[LOG] Preloaded target /home/apm/.config/wallpapers/hk1.jpg in 33.76ms -> Pixel size: [2498, 1522]
[LOG] Preloaded target /home/apm/.config/wallpapers/hk5.jpg in 29.56ms -> Pixel size: [2908, 1500]
[LOG] hyprpaper socket started at /tmp/hypr/7d914cd427b36d5ec8acb06e415cdf2b846f1648_1676314472/.hyprpaper.sock (fd: 4)
[LOG] configure for eDP-2
[LOG] handlePreferredScale: 1.40 for 55ae8a50bd40
[LOG] Buffer created for target /home/apm/.config/wallpapers/hk5.jpg, Shared Memory usage: 16.4MB
[LOG] Buffer created for target /home/apm/.config/wallpapers/hk1.jpg, Shared Memory usage: 16.4MB
[LOG] Total SM usage for all buffers: 32.7MB
[LOG] Pool buffer missing for available target??
[LOG] Buffer created for target /home/apm/.config/wallpapers/hk5.jpg, Shared Memory usage: 16.4MB
[LOG] Buffer created for target /home/apm/.config/wallpapers/hk1.jpg, Shared Memory usage: 16.4MB
[LOG] Total SM usage for all buffers: 65.4MB
zsh: segmentation fault (core dumped)  build/hyprpaper
```

**Comment by vaxerski** [comment]
your scale leaves fractional pixels. That's why I suggested `std::round`

**Comment by cijo7** [comment]
@vaxerski  now this should be fixed.

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
