### PR TITLE
Allow multiple read from IPC + some refactor

### PR DESCRIPTION
**Pull request by cylian914**
The previous implementation was closing the connection right after 1 message (ligne 87) so i couldn't send multiple request with the same socket, this fix it.

### CODE REVIEW

**Comment by vaxerski** [comment]
that is intentional though.

**Comment by cylian914** [comment]
Why ?

**Comment by vaxerski** [comment]
reading more can block, besides, there is no point. Just open a new socket connection?

**Comment by cylian914** [comment]
How can it block ? the only thing that could happen is the client crash right after the data is send (so it doesn't client doesn't read hyprpaper message) and in that case it crash hyprpaper but it can also happen the old version. Also when the client disconnect it will send a message of 0 char and that is expected, with `if (messageSize == 0) break;` (line 61) it will close the socket connection. Nothing should block ?

**Comment by vaxerski** [comment]
the client can send a message and then do nothing, blocking hyprpaper.

**Comment by cylian914** [comment]
its the same thing with the old one ? For the old one it will block at line 62 waiting for the data but the new one will block at line 59. 

Also the old one could crash if you connect but immediately exit because  it would then try to `write(ACCEPTEDCONNECTION, m_szReply.c_str(), m_szReply.length());' having no connection to send (i didn't test it but it should do it)

**Comment by vaxerski** [comment]
true that... Fine I guess. I'll review this tomorrow. One thing I can definitely say this MR needs is a `clang-format`

**Review by vaxerski — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
