### PR TITLE
CMakeLists: look for wayland.xml protocol in wayland-scanner pkgdata

### PR DESCRIPTION
**Pull request by andresilva**
This is required to build on NixOS after https://github.com/NixOS/nixpkgs/pull/214906 (which is already in nixos-unstable-small).

### CODE REVIEW

**Comment by andresilva** [comment]
For reasons that I don't understand this doesn't build on current `nixos-unstable` (i.e. before https://github.com/NixOS/nixpkgs/pull/214906) unless wayland-scanner is declared as a `buildInput` instead of `nativeBuildInput`.

**Comment by fufexan** [comment]
It will work with `wayland-scanner` left in `nativeBuildInputs`, but you have to move `pkg-config` to `depsBuildBuild`. (one layer higher in the hierarchy than `nativeBuildInputs`)

**Comment by andresilva** [comment]
@fufexan That doesn't seem to work still. The PR works as is on `nixos-unstable-small` btw, and both `pkg-config` and `wayland-scanner` are declared as `nativeBuildInputs` on the other `hyprwm` projects.

**Comment by fufexan** [comment]
I'll take a look. Btw if you're referring to https://nixpk.gs/pr-tracker.html?pr=214906, it's got to nixos-unstable, so it's safe to update the flake as well.

**Comment by fufexan** [comment]
> For reasons that I don't understand this doesn't build on current `nixos-unstable` (i.e. before [NixOS/nixpkgs#214906](https://github.com/NixOS/nixpkgs/pull/214906)) unless wayland-scanner is declared as a `buildInput` instead of `nativeBuildInput`.

It just built for me.

**Comment by andresilva** [comment]
That's weird. Did it build for you before updating nixos-unstable?

**Comment by fufexan** [comment]
> That's weird. Did it build for you before updating nixos-unstable? It works for me with latest nixos-unstable, but that also works with `pkg-config` in `nativeBuildInputs`.

Haven't tried that. Anyway, I've noticed `pkg-config` should be in both `depsBuildBuild` and `nativeBuildInputs`, so that it can "see" dependencies "lower" than itself. This is important for cross compiling at least.

**Review by fufexan — APPROVED** [review]

**Pull request merged**
