### PR TITLE
fix: build failed in big-endian system

### LINKED ISSUE #40: /wrkdirs/usr/ports/x11/hyprpaper/work/hyprpaper-f77a664/src/helpers/Jpeg.cpp:8:2: error: #error "your system is not little endian, jpeg will not work, ping vaxry or something"
While building on FreeBSD/powerpc64:
```
/usr/local/bin/g++12 -DGIT_BRANCH=\"main\" -DGIT_COMMIT_HASH=\"f77a664\" -DGIT_COMMIT_MESSAGE="\"<unknown>\"" -DGIT_DIRTY=\"portbld\" -I/wrkdirs/usr/ports/x11/hyprpaper/work/hyprpaper-f77a664/. -isystem /usr/local/include/libepoll-shim -isystem /usr/local/include/cairo -isystem /usr/local/include/glib-2.0 -isystem /usr/local/lib/glib-2.0/include -isystem /usr/local/include/pixman-1 -isystem /usr/local/include/freetype2 -isystem /usr/local/include/libpng16 -O2 -pipe  -fstack-protector-strong -Wl,-rpath=/usr/local/lib/gcc12  -Wl,-rpath=/usr/local/lib/gcc12 -O2 -pipe  -fstack-protector-strong -Wl,-rpath=/usr/local/lib/gcc12  -Wl,-rpath=/usr/local/lib/gcc12  -DNDEBUG -std=c++23 -DWLR_USE_UNSTABLE -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -D_THREAD_SAFE -pthread -MD -MT CMakeFiles/hyprpaper.dir/src/helpers/Jpeg.cpp.o -MF CMakeFiles/hyprpaper.dir/src/helpers/Jpeg.cpp.o.d -o CMakeFiles/hyprpaper.dir/src/helpers/Jpeg.cpp.o -c /wrkdirs/usr/ports/x11/hyprpaper/work/hyprpaper-f77a664/src/helpers/Jpeg.cpp
/wrkdirs/usr/ports/x11/hyprpaper/work/hyprpaper-f77a664/src/helpers/Jpeg.cpp:8:2: error: #error "your system is not little endian, jpeg will not work, ping vaxry or something"
    8 | #error "your system is not little endian, jpeg will not work, ping vaxry or something"
      |  ^~~~~
```

This is indeed big-endian system :)

@vaxerski

### PR DESCRIPTION
**Pull request by tobiichi3227**
Close #40

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
ye but what about png

**Comment by tobiichi3227** [comment]
I checked cairo library source code.
They have do this part.

**Comment by vaxerski** [comment]
have you checked this on a big endian?

**Comment by tobiichi3227** [comment]
Yes.
I checked on qemu-powerpc64 platform by writing a simple cairo program.

**Review by vaxerski — APPROVED** [review]
alright then, I can't test, but who even uses big endian, tbh :P

**Comment by vaxerski** [comment]
thanks!

**Comment by tobiichi3227** [comment]
Indeed.
I even cannot run hyprland on qemu-powerpc64.

**Pull request merged**
